# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScannerFlow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScannerFlow
  
    pod 'Cartography', '~> 3.0'

  target 'ScannerFlowTests' do
    # Pods for testing
  end

end
